Algoritmo "consumo"

Var

   distanciaPercorrida : inteiro
   combustivelGasto : real
   consumoMedio : real

Inicio

              escreva("Distancia percorrida: ")
      leia(distanciaPercorrida)
              escreva("Combustível gasto: ")
      leia(combustivelGasto)

consumoMedio <- distanciaPercorrida / combustivelGasto

              escreva("Consumo medio = ", consumoMedio:6:3)
Fimalgoritmo